global using JyunrcaeaFramework.Core;
global using JyunrcaeaFramework.Graphics;
global using JyunrcaeaFramework.Objects;
global using JyunrcaeaFramework.Collections;
global using JyunrcaeaFramework.Audio;
global using JyunrcaeaFramework.Structs;
global using JyunrcaeaFramework.EventSystem;
global using JyunrcaeaFramework.Interfaces;
global using JyunrcaeaFramework.Utils;
